# Permalinks
permalink: /:categories/:title/

# Site settings
title: Rob Uridge
email: rob@uridge.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
blogurl: "/blog/"
projectsurl: "/projects/"
url: "http://www.uridge.com" # the base hostname & protocol for your site
twitter_username: roburidge
github_username:  roburidge

# Build settings
markdown: kramdown
