# Permalinks
permalink: /:categories/:title/

# Site settings
title: Rob Uridge
email: rob@uridge.com
description: > # this means to ignore newlines until "baseurl:"
  The portfolio and blog of Rob Uridge
baseurl: "" # the subpath of your site, e.g. /blog/
blogurl: "/blog/"
projectsurl: "/projects/"
url: "http://www.uridge.com" # the base hostname & protocol for your site
twitter_username: roburidge
github_username:  roburidge

# Build settings
markdown: kramdown
